### ISSUE TITLE
Tool doesn't work with 3.2.2 on Raspi

### ISSUE THREAD

**Issue by richrarobi** [emlyn/sonic-pi-tool#8]
For 3.2.2, I changed some paths, lines 189 and 289, which might not be perfect, but it then worked.
around line 188:-
ruby_paths = ['server/native/ruby/bin/ruby'] server_paths = ['server/ruby/bin/sonic-pi-server.rb', 'server/bin/sonic-pi-server.rb', 'server/ruby/bin/sonic-pi-server.rb']
around line 289:-
default_paths = ('./Sonic Pi.app', # Check current dir first './app', '~/Applications/Sonic Pi.app', # Then home dir '/Applications/Sonic Pi.app', # Finally standard dirs '/opt/sonic-pi-3.2.2/app', '/usr/lib/sonic-pi')

I also changed **port** to   **osc_port** on line 100 (might be wrong there !!??)

p.s. The ports may also be wrong as per the previous post. It works ok until you run the gui - this kills the server. (I may have caused this problem by not cloning the original - investigating... it might be any of the ports - trying websocket port - just the same as before.)

Also you need a symlink : sudo ln -s /usr/bin/sonic-pi-3-2-2 /usr/bin/sonic-pi

**Comment by emlyn** [comment]
I've fixed some of this:
- The port bug is fixed (it now checks both osc_port and cmd_port).
- It now looks in the sonic-pi-3-2-2 folder, so it should work without the symlink.
- The default OSC port is updated to 4560 as used by recent Sonic Pi versions.

Unfortunately the server getting killed when the GUI starts is outside of my control, it would need changes to Sonic Pi itself. I think Sonic Pi does this in case there are stray processes lying around from a previous run that failed to shut down properly.

There's also an issue with determining the command port. Old versions used port 4557, but newer versions use a random port. When started with the GUI, this port is written to a log file, so I now read that log file to find the port. But that doesn't work when starting the server from sonic-pi-tool. I think the easiest is to also write to that log file from sonic-pi-tool, but I haven't implemented that yet.
For now you can look at the server output for the line `Listen port: nnnnn`, and then pass `--cmd-port nnnnn` to sonic-pi-tool.

**Comment by richrarobi** [comment]
I don't know if this will be of any help, I am still running headless.

There seems to be a port number issue, which might be with sonic and not the tool.......  This is possibly around sockets, because a couple of times it managed to hang  my mint X-windows (this is quite rare). Anyway, output from another run is attached. I tried changing the 127.0.0.1 to 0.0.0.0 in the tool (about 4 or 5 places) but it seemed to make no difference.

[out.txt](https://github.com/emlyn/sonic-pi-tool/files/4640073/out.txt)

ps. If I run sonic-pi normally, the tool works from another ssh terminal on a different system, using **check** or **eval "play :C4"**.

**Comment by emlyn** [comment]
I've made the server write its output to the normal sonic pi logs, so I think that should fix the port detection when you try to send it a command - does it work better now?

**Comment by richrarobi** [comment]
This works a lot better. However....There is a weird issue.
If I add ampersand on the end of the start server command to let it run in background, the X-windows session (and seemingly Mint on that system) locks up. (I notice a flicker as sonic-server is started, so it may send something odd to X then).

I would do the ampersand thing to start the server using cron.

I have to go to another PC, login to the pi (ssh) and reboot the pi to clear the problem. X on the first screen then unlocks and works normally.
p.s. does it matter I am using python3? I change the shebang line to add a 3 at end.


**p.p.s. Should a normal run of start-server exit at the end? i.e. to go back to command prompt. It doesn't.**

**Comment by emlyn** [comment]
That locking up of the system seems very strange to me, I'm not really sure what's going on. It might be worth asking a question on the Sonic Pi [forums](https://in-thread.sonic-pi.net/), as someone there might have a better idea.

It's fine to use Python 3 - it should be compatible with both 2.7 and 3.

Currently start-server doesn't exit at the end, but stays in the foreground so that you can see any log messages, and shut it down with Ctrl-C.
However, it might be possible to add a `--background` flag to leave it running in the background and return to the command prompt. In that case it might be useful to add a `shutdown-server` command to shut it down. I'll add an issue, and maybe get around to adding this at some point.
EDIT: #11

**Comment by richrarobi** [comment]
I think it would be good to have those "background" options. In the meantime, I have a (crappy) 5" screen that I have put on the pi. It doesn't mind being switched off, so I can leave a "dark" session running directly on the pi (with a crappy keyboard attached) ..... It gets round the issue of headless, although I can probably not start it on boot.
Tend to agree on the hanging issue - it is more likely a sonic-pi problem - will raise there.

p.s. Thanks for the attention, and keep safe!

**Comment by emlyn** [comment]
The latest version can now start the server in the background with:
`sonic-pi-tool.py start-server --background`
Hopefully that's useful for you.
As part of this change I removed python 2 support because it was getting complicated to maintain compatibility with both python 2 and 3 (there is still a python2 branch, but that doesn't support the `--background` flag)
